### ISSUE TITLE
package ‘KOMODO2’ is not available (for R version 4.0.1)

### ISSUE THREAD

**Issue by g1o** [franciscolobo/KOMODO2#11]
Tested with R version > 4
Erro: Failed to install 'KOMODO2' from GitHub:
  (convertido do aviso) package ‘preprocessCore’ is not available (for R version 4.0.1)

Guessing the range it works is for R versions >=3.6 <4 for now

**Comment by fcampelo** [comment]
Check on my fork: https://github.com/fcampelo/KOMODO2 , already sorted out.

I'm finishing the tests and will send a PR to Francisco by the end of this week.
